// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0hUMq4bSwrGf-iYSDF_5s7uc4JhWpmfQ',
    appId: '1:918077964106:web:806632265da944d8768bb3',
    messagingSenderId: '918077964106',
    projectId: 'la-masseria-app',
    authDomain: 'la-masseria-app.firebaseapp.com',
    storageBucket: 'la-masseria-app.appspot.com',
    measurementId: 'G-PCK9HPPR9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkc28I2iGg8AHknUREwSd5QSYJIRqeGA',
    appId: '1:918077964106:android:602d8b97388e7b8e768bb3',
    messagingSenderId: '918077964106',
    projectId: 'la-masseria-app',
    storageBucket: 'la-masseria-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiIn-8RsuLdTgr6KsW7wdt7S6KcXbcRug',
    appId: '1:918077964106:ios:eb1961c2d9863b32768bb3',
    messagingSenderId: '918077964106',
    projectId: 'la-masseria-app',
    storageBucket: 'la-masseria-app.appspot.com',
    iosClientId: '918077964106-h04mbkve9lku46remaee4js7nu79k3ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiIn-8RsuLdTgr6KsW7wdt7S6KcXbcRug',
    appId: '1:918077964106:ios:eb1961c2d9863b32768bb3',
    messagingSenderId: '918077964106',
    projectId: 'la-masseria-app',
    storageBucket: 'la-masseria-app.appspot.com',
    iosClientId: '918077964106-h04mbkve9lku46remaee4js7nu79k3ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
